---
# Red Hat Satellite Automation Playbooks
# Collection requirements
collections:
  - name: ansible.posix
  - name: redhat.satellite_operations
    version: ">=3.0.1,<4.0.0"
  - name: redhat.satellite
    # smart_proxy_refresh was added in 5.9.0.
    version: ">=5.9.0,<6.0.0"
