---
# Red Hat Satellite Automation Playbooks
# Collection requirements
collections:
  - name: ansible.posix
  - name: redhat.satellite_operations
    version: ">=1.0.0"
  - name: redhat.satellite
    # content_import_version and content_import_info were added in 4.1.0.
    version: ">=4.1.0"
